FROM php:8.3-fpm-alpine AS php-ext-builder

RUN apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        freetype-dev \
        icu-dev \
        imagemagick-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libwebp-dev \
        libzip-dev \
        sqlite-dev && \
    docker-php-ext-install -j"$(nproc)" calendar pdo_sqlite && \
    docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
    docker-php-ext-install -j"$(nproc)" gd intl zip && \
    pecl install imagick && \
    docker-php-ext-enable imagick

FROM php:8.3-fpm-alpine

WORKDIR /var/www/html

RUN apk add --no-cache \
        curl \
        dcron \
        dumb-init \
        freetype \
        icu-data-full \
        icu-libs \
        imagemagick \
        libgomp \
        libjpeg-turbo \
        libpng \
        libwebp \
        libzip \
        nginx \
        shadow \
        sqlite \
        tzdata

COPY --from=php-ext-builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=php-ext-builder /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/
