services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/Toronto'
      WALLOS_BACKUP_PATH: '/var/www/html/backups'
      WALLOS_BACKUP_RETENTION_DAYS: '30'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
      - './backups:/var/www/html/backups'
    restart: unless-stopped
